export const RANDOM_USER_DATA_START = 'RANDOM_USER_DATA_START';
export const RANDOM_USER_DATA_SUCCESS = 'RANDOM_USER_DATA_SUCCESS';
export const RANDOM_USER_DATA_ERROR = 'RANDOM_USER_DATA_ERROR';
export const ADD_FAVOURITE='ADD_FAVOURITE';
export const UN_FAVOURITE='UN_FAVOURITE';